### ISSUE TITLE
[suggestions] commands

### ISSUE THREAD

**Issue by Bass2style** [Flanks255/simplyutilities#1]
**Describe the bug**
Hi,

it's not really a bug, but a personnal advice about the commands system.

i think that the commands are too complicated for the usage needed (for example to set or tp to a home.)
is it possible to edit the commands to get a more classic command like /sethome, /home, /spawn etc ? or at least make possible to enable aliasses in the config.

Thanks for the mod, it's the only alternative atm on Forge 1.18, so it's nice to have a mod that can set homes etc.

Have a Nice day.

edit : mod description says also that Homes etc are configurable, but, you can't edit the max homes you can set, or i don't find it in the config, any way to get a custom amount of homes ?
edit2 : is it also possible to add a /back command to get back to the last death/point (before a TP for example) ?

**Comment by Flanks255** [comment]
Ill look into adding a config option to put them in the global namespace, i put them behind /simplyutilities or /su incase there is another mod doing /home etc, would cause problems.

That config is in the server config folder, Single player its: Minecraft/saves/[worldname]/serverconfig/,
On a server, its world/serverconfig/


ill try to look into a /back at some point.

**Comment by Bass2style** [comment]
Hi, thanks for your reply.

i also think that aliases are a safer option for compatibility/conflicts reasons.

i found it, thanks. :D

thanks, because it's really helpfull, mainly when you die, a bit cheaty, but meh. xD

have a nice day.
